# Generated by Django 3.0.8 on 2020-07-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriverDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=50)),
                ('lic_no', models.CharField(max_length=20)),
                ('experience', models.IntegerField()),
                ('complaints', models.CharField(max_length=100)),
                ('route', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'driver_details',
            },
        ),
        migrations.CreateModel(
            name='ParentsDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=50)),
                ('student_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('blood_group', models.CharField(max_length=10)),
                ('educational_qualification', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'parents_details',
            },
        ),
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=70)),
                ('age', models.IntegerField()),
                ('class_name', models.CharField(db_column='class', max_length=30)),
                ('section', models.CharField(max_length=20)),
                ('blood_group', models.CharField(max_length=10)),
                ('parent_name', models.CharField(max_length=50)),
                ('parent_phone_number', models.CharField(max_length=15)),
                ('class_teacher', models.CharField(max_length=50)),
                ('favourite_sport', models.CharField(max_length=50)),
                ('favourite_subject', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'student_details',
            },
        ),
        migrations.CreateModel(
            name='TeacherDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=50)),
                ('head_of_class', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=20)),
                ('years_of_experience', models.IntegerField()),
                ('educational_qualification', models.CharField(max_length=50)),
                ('complaints', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'teacher_details',
            },
        ),
    ]
