# Generated by Django 3.0.8 on 2020-07-19 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_parentsdetails_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverdetails',
            name='subject',
        ),
    ]
