# Generated by Django 3.0.8 on 2020-07-19 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200719_0434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentsdetails',
            name='section',
        ),
        migrations.AlterField(
            model_name='parentsdetails',
            name='parent_name',
            field=models.ForeignKey(db_column='parent_name', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='main_app.StudentDetails'),
        ),
    ]
